name: Docker Playwright Tests for esup-otp-cas

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Run Playwright tests
        run: docker compose -f src/etc/docker-compose.yml --profile playwright --profile with-esup-emargement up --abort-on-container-exit --exit-code-from playwright playwright
      - name: Upload Playwright report and results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: |
            src/etc/docker/playwright/playwright-report
          if-no-files-found: ignore
